<?php

namespace App\Http\Requests\Finance\Accounting;

use App\Models\Finance\Currency;
use App\Models\Finance\Ledger;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StorePettyCashFundRequest extends FormRequest
{
    private const SAFE_TEXT_REGEX = "/^[\\pL\\pN\\s\\-\\.,&()\\/'#]+$/u";

    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'name' => is_string($this->name) ? trim(preg_replace('/\s+/u', ' ', $this->name)) : $this->name,
        ]);
    }

    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:100', 'regex:' . self::SAFE_TEXT_REGEX, 'not_regex:/<[^>]*>/'],
            'code' => ['prohibited'],
            'ledger_uuid' => ['required', 'string', 'size:36', Rule::exists('ledgers', 'uuid')],
            'currency_uuid' => ['required', 'string', 'size:36', Rule::exists('currencies', 'uuid')],
            'custodian_user_uuid' => ['nullable', 'string', 'size:36', Rule::exists('users', 'uuid')->where(fn ($q) => $q->where('is_active', true))],
            'imprest_amount' => ['required', 'numeric', 'gt:0'],
            'min_reorder_amount' => ['nullable', 'numeric', 'gte:0', 'lte:imprest_amount'],
            'is_active' => ['sometimes', 'boolean'],
        ];
    }

    public function after(): array
    {
        return [function () {
            $ledgerUuid = (string) ($this->input('ledger_uuid') ?? '');
            $currencyUuid = (string) ($this->input('currency_uuid') ?? '');

            if ($ledgerUuid === '' || $currencyUuid === '') {
                return;
            }

            $ledger = Ledger::query()
                ->select(['id', 'currency_id'])
                ->where('uuid', $ledgerUuid)
                ->first();
            $currency = Currency::query()
                ->select(['id'])
                ->where('uuid', $currencyUuid)
                ->first();

            if (! $ledger || ! $currency) {
                return;
            }

            if ((int) $ledger->currency_id !== (int) $currency->id) {
                $this->validator->errors()->add('currency_uuid', 'Selected currency must match the currency of the chosen petty cash ledger.');
            }
        }];
    }

    public function messages(): array
    {
        return [
            'name.required' => 'Fund name is required.',
            'name.max' => 'Fund name must not exceed 100 characters.',
            'name.regex' => 'Fund name contains invalid characters.',
            'name.not_regex' => 'Fund name must not contain HTML or script tags.',
            'code.prohibited' => 'Fund code is auto-generated by the system. Remove it and try again.',
            'ledger_uuid.required' => 'Please select the petty cash ledger.',
            'ledger_uuid.size' => 'The selected petty cash ledger is invalid.',
            'ledger_uuid.exists' => 'The selected petty cash ledger does not exist.',
            'currency_uuid.required' => 'Please select the currency.',
            'currency_uuid.size' => 'The selected currency is invalid.',
            'currency_uuid.exists' => 'The selected currency does not exist.',
            'custodian_user_uuid.size' => 'The selected custodian is invalid.',
            'custodian_user_uuid.exists' => 'The selected custodian is invalid or inactive.',
            'imprest_amount.required' => 'Imprest amount is required.',
            'imprest_amount.numeric' => 'Imprest amount must be a valid number.',
            'imprest_amount.gt' => 'Imprest amount must be greater than zero.',
            'min_reorder_amount.numeric' => 'Minimum reorder amount must be a valid number.',
            'min_reorder_amount.gte' => 'Minimum reorder amount cannot be negative.',
            'min_reorder_amount.lte' => 'Minimum reorder amount cannot be greater than the imprest amount.',
            'is_active.boolean' => 'Fund status must be valid.',
        ];
    }
}
